src/SumoCoders/FrameworkUserBundle/Entity/SumoUser.php
<?php

namespace SumoCoders\FrameworkUserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use SumoCoders\FrameworkMultiUserBundle\Entity\BaseUser;
use SumoCoders\FrameworkMultiUserBundle\Security\PasswordResetToken;

/**
 * @ORM\Entity(repositoryClass="SumoCoders\FrameworkUserBundle\Repository\SumoUserRepository")
 * @ORM\Table()
 */
class SumoUser extends BaseUser
{
    public function __construct(
        string $plainPassword,
        string $displayName,
        string $email,
        int $id = null,
        PasswordResetToken $token = null
    ) {
        parent::__construct($email, $plainPassword, $displayName, $email, $id, $token);
    }

    public function getRoles(): array
    {
        return ['ROLE_USER'];
    }
}

src/SumoCoders/FrameworkUserBundle/Resources/views/Index/index.html.twig
{% extends '::base.html.twig' %}

{% block header_title %}
  <h2>
    {{ 'user.header.index'|trans|capitalize }}
  </h2>
{% endblock %}

{% block header_navigation %}
  <a class="btn btn-success" href="{{ path('sumo_coders.user.route.add_user') }}">
    {{ icon('plus') }}
    {{ 'user.actions.add.user'|trans|capitalize }}
  </a>
{% endblock %}

{% block main %}
  <table class="table table-hover">
    <thead>
      <tr>
        <th>{{ 'user.datagrid.username'|trans|capitalize }}</th>
        <th>{{ 'user.datagrid.email'|trans|capitalize }}</th>
        <th>{{ 'user.datagrid.type'|trans|capitalize }}</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
        <tr{% if user.isBlocked() %} class="text-muted"{% endif %}>
          <td>{{ user.displayName }}</td>
          <td>{{ user.username }}</td>
          <td>
            {% for role in user.roles %}
              {{ ('user.types.' ~ role)|trans|capitalize }}<br>
            {% endfor %}
          </td>
          <td class="action">
            {% if not user.isBlocked() and app.user.canSwitchTo(user) %}
              {# todo switch route to homepage? #}
              <a
                href="{{ path('sumocoders_frameworkexample_bootstrap_select2') }}?_switch_user={{ user.username }}"
                class="fa fa-refresh confirm"
                data-toggle="tooltip"
                title="{{ 'user.datagrid.actions.switchTo'|trans }}"
                data-message="{{ 'user.dialogs.messages.confirmSwitch'|trans({'%user%': user.username}) }}"
              >
                <span class="hide">{{ 'user.datagrid.actions.switchTo'|trans }}</span>
              </a>
            {% endif %}
          </td>
          <td class="action">
            <a
              {% if user is admin %}
                href="{{ path('sumo_coders.user.route.edit_admin', {'id': user.id}) }}"
              {% else %}
                href="{{ path('sumo_coders.user.route.edit_user', {'id': user.id}) }}"
              {% endif %}
              class="fa fa-pencil"
              data-toggle="tooltip"
              title="{{ 'datagrids.actions.edit'|trans }}"
            >
              <span class="hide">
                {{ 'datagrids.actions.edit'|trans }}
              </span>
            </a>
          </td>
          <td class="action">
            <a
              href="{{ path('sumo_coders.user.route.block', {'id': user.id}) }}"
              {% if user.isBlocked() %}
                class="fa fa-check confirm" data-toggle="tooltip"
                title="{{ 'user.datagrid.actions.unblock'|trans }}"
                data-message="{{ 'user.dialogs.messages.confirmUnblock'|trans({'%user%': user.username}) }}"
              {% else %}
                class="fa fa-ban confirm" data-toggle="tooltip"
                title="{{ 'user.datagrid.actions.block'|trans }}"
                data-message="{{ 'user.dialogs.messages.confirmBlock'|trans({'%user%': user.username}) }}"
              {% endif %}
            >
              <span class="hide">
                {% if user.isBlocked() %}
                  {{ 'user.datagrid.actions.unblock'|trans }}
                {% else %}
                  {{ 'user.datagrid.actions.block'|trans }}
                {% endif %}
              </span>
            </a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}